export { default as DPDHLMainHeadline} from './dpdhl-main-headline.svelte'
export { default as DPDHLTopline} from './dpdhl-topline.svelte'
export { default as DPDHLSecondaryHeadline} from './dpdhl-secondary-headline.svelte'
export { default as DPDHLParagraphHeader} from './dpdhl-paragraph-header.svelte'
export { default as DPDHLIntroductionLarge } from './dpdhl-introduction-large.svelte'
export { default as DPDHLIntroductionSmall } from './dpdhl-introduction-small.svelte'
export { default as DPDHLCopy } from './dpdhl-copy.svelte'
export { default as DPDHLEmphasis } from './dpdhl-emphasis.svelte'
export { default as DPDHLCaption } from './dpdhl-caption.svelte'
export { default as DPDHLQuotation} from './dpdhl-quotation.svelte'
export { default as DPDHLMarginalia} from './dpdhl-marginalia.svelte'
